### ISSUE TITLE
リリース日の決定

### ISSUE THREAD

**Issue by takai-tamb** [sizukutamago/dialogflow-bot#14]
@75asa @sizukutamago 
最近質問のあったものに関しては登録済です。
具体的なリリース日を決定したいです。

**Comment by 75asa** [comment]
> FAQボットのリリースについて相談です。
ある程度最近質問があったものに関しては、登録が完了したのでリリースしたいと考えております。
#d_faq_bot_test こちらのチャンネル名をリネームする形でのリリース（社内周知）でいいのでしょうか？別途作業が必要ですか？
別途作業が行われる場合、年内リリースできそうでしょうか？

**Comment by 75asa** [comment]
@sizukutamago チャネルは別で作ったがいいと思うんですがどうでしょう？
e.g. #t_faq

**Comment by 75asa** [comment]
リリースしました！w
あとは説明だけですかね〜
どうしようかな

**Comment by 75asa** [comment]
@takai-tamb 説明はコーポレートからおねがいしたいです 🙏🏾

**Comment by takai-tamb** [comment]
@75asa 
私がまごついてるうちに修正＆リリースありがとうございます・・・！！！！！！！
周知は管理部の方からだします！

**Comment by 75asa** [comment]
リリース日は今日
